language: ruby
rvm:
  - 2.6.3
  - 2.5.5
  - 2.4.6
before_script:
  - bundle exec appraisal install --jobs=3
script:
  - bundle exec rubocop
  - bundle exec appraisal rails5_0 rspec
  - bundle exec appraisal rails5_1 rspec
  - bundle exec appraisal rails5_2 rspec
  - bundle exec appraisal avro-patches-5_0 rspec
  - bundle exec appraisal avro-patches-0_3_4-rails5_1 rspec
  - bundle exec appraisal avro-patches-0_3_4-rails5_2 rspec
  - bundle exec appraisal avro-patches-rails5_1 rspec
  - bundle exec appraisal avro-patches-rails5_2 rspec
