[package]
name = "avromatic"
version = "0.1.0"
authors = ["Kyle Phelps <kphelps@salsify.com>"]
edition = "2018"

[dependencies]
failure = "*"
lazy_static = "*"
rutie = { git = "https://github.com/danielpclark/rutie", branch = "master" }
avro-rs = { git = "https://github.com/kphelps/avro-rs", branch = "feature/reference-types" }

[lib]
name = "avromatic"
crate-type = ["dylib"]